# Pasted from LiquidBounce's bug report template lol
name: 🐞 Bug report
description: Create a report to help us squash (fix) it
labels: "bug"
title: "[BUG] "

body:
  - type: input
    attributes:
      label: Sigma Rebase Build/Version
      description: Which version of LiquidBounce does this bug affect?
      placeholder: A release build OR a commit hash for nightly, e.g. 1.0.0 (release), fb19c7a (nightly).
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Operating System
      description: What OS has this bug? (if applicable, e.g. something works on Linux but not on Windows)
      multiple: true
      options:
        - macOS (how dare you use OSX-KVM to test your cross platform software instead of buying an expensive Mac that will be thrown into the trash)
        - Linux (only good OS in 2025, refers to one of the Linux distros, not the kernel)
        - "Windows 10 (last acceptable version of Windows, the last good version of Windows is 7, but that's old)"
        - Windows 11 (1st unacceptable version of Windows)

  - type: textarea
    attributes:
      label: Describe the bug
      description: Clear and thorough explanation of the bug.
      placeholder: I was doing X expecting Y to happen, but Z happened instead.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Minimum steps required to reproduce the bug.
      placeholder: |
        - Go to 'Meezer adoption UI'
        - Click on 'Adopt a Meezer'
        - Scroll down to 'Info'
        - See a black cat being attacked by the newly adopted Meezer, because I didn't play with Meezer for long enough
    validations:
      required: true

  - type: textarea
    attributes:
      label: Client Log
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
