# Also pasted from LiquidBounce
name: ✨ Feature request
description: Suggest an idea for this project
labels: "enhancement"
title: "[FEATURE] "

body:
  - type: textarea
    attributes:
      label: Describe your feature request.
      description: |
        A clear and concise description of what the feature request is.
      placeholder: I've always wanted to be able to adopt a Meezer from the client UI
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
