name: Build and Release JAR

on:
  push:
    branches:
      - pojav

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and push tag
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git tag -f pojav-nightly
          git push --force https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git pojav-nightly

      - name: Download built JAR
        uses: actions/download-artifact@v4
        with:
          name: built-jar
          path: target/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_PAT }}
          tag_name: pojav-nightly
          prerelease: true
          files: |
            target/*.jar
            release/sigma-jello-5.1.0.json